
##spring config
spring:
  datasource:
    ##url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=vefuture
    username: postgres
    password: 7241
