##server config
server:
  port: 8083
  servlet:
    context-path: /bigbottle
  address: 0.0.0.0

##配置日志输出
logging:
  level:
    root: info #全局目录
    com.vefuture.big_bottle.web.vefuture: debug  # 指定包的日志级别
    org.mybatis: trace
    org.springframework.security: info
    org.springframework.web.socket: DEBUG
  file:
    # 定义日志文件的根目录，可以根据需要修改
    path: ./logs
  config: classpath:logback-spring.xml  # 指定使用自定义 logback 配置

##spring config
spring:
  application:
    name: big_bottle
  profiles:
    active: dev  # 开发环境，部署时改为 prod、uat 等
  ##引入其他配置类
  config:
    import:
      - classpath:bigbottle_config.yml
      - classpath:other_config.yml
  ##使用默认的hikari连接池
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000      # 空闲超时时间，单位毫秒
      connection-timeout: 30000 # 获取连接超时时间，单位毫秒
      max-lifetime: 1800000     # 连接最大存活时间，单位毫秒
mybatis-plus:
  # 指定扫描 mapper 接口的包路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 指定实体类别名包，便于在 xml 中简化全限定类名
  type-aliases-package: com.vefuture.**.entity
  configuration:
    #配置是否将下划线自动映射为驼峰命名
    map-underscore-to-camel-case: true
    # 输出 SQL 日志，便于调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 更多高级配置，可根据需要添加
  global-config:
    db-config:
      id-type: auto  # 主键策略（自动增长）
      logic-delete-field: is_delete  # 逻辑删除字段名 (保持不变或按需修改)
      logic-delete-value: "true"     # 值：表示已删除的值 (从 1 改为 true)
      logic-not-delete-value: "false" # 值：表示未删除的值 (从 0 改为 false)
      #logic-delete-value: 1  # 逻辑删除的值
      #logic-not-delete-value: 0
##线程池配置参数
task:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 1000
    keep-alive-seconds: 300
### 系统监控配置参数
management:
  #server:
    #port: 8384  #如果设置该端口, 那么应用的context-path就不起作用了
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # include: health,info  # 只暴露 health 和 info
        include: "*"         # 暴露所有启用的 Web 端点 (开发时常用，生产需谨慎)
        # exclude: env,beans # 可以用 exclude 来排除某些端点
      base-path: /actuator #/monitor 这个地方可以设置其他路径
##配置websocket
websocket:
  allowed-origins:
    - http://localhost:3001
    - http://localhost:3000
    - http://127.0.0.1:5500