
##spring config
spring:
  datasource:
    ##url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:postgresql://18.176.28.203:5432/postgres?currentSchema=vefuture
    username: postgres
    password: BigBottle_wu
bigbottle:
  counttimes:
    ##每天上传最大次数
    max: 1
    ##获取最后几张小票
    lastnum: 5