
###配置coze模型参数

bigbottle:
  ##coze模型相关配置
  coze:
    coze_url: https://api.coze.com/v1/workflow/run
    coze_workflow_id: 7482017874254037010  #可用的
    coze_token: Bearer pat_Ajze2x0PeAooelnbBOZIlbQBQMrPEiq7Lcklt4auDlmnkTyWYmbUZMzDIQ2mUmxc
  dify:
    dify_app_key: app-tUljvhHWk4TWYhJGg4s73kig
    dify_url: https://api.dify.ai/v1/workflows/run

  counttimes:
    ##每天上传最大次数
    max: 3
    ##获取最后几张小票
    lastnum: 5
